### ISSUE TITLE
Failing to properly sell items

### ISSUE THREAD

**Issue by naoliv** [k5md/Steam-Bulk-Sell-webextension#3]
While selecting some items to be sold I can see that it's giving `NaN` for the prices:

![](https://user-images.githubusercontent.com/982338/95692816-0138d580-0bff-11eb-9ff3-bc23fb91be19.png)

While with some items it doesn't get (or set) any price:

![](https://user-images.githubusercontent.com/982338/95692831-1281e200-0bff-11eb-8ea7-7a8148bfb945.png)

Probably due to the NaNs, the objects aren't listed on the market, despite it's saying that it's selling the them.

**Comment by naoliv** [comment]
Maybe it could be related with the comma/dot separator?
For example:

![](https://user-images.githubusercontent.com/982338/95693344-401c5a80-0c02-11eb-9bab-03a7b62c04f0.png)

While on the right side it displays all values with a comma, it only accepts a dot.

**Comment by naoliv** [comment]
Well, I did try to sell the items using a dot in the value, bit no market listing was created...

**Comment by k5md** [comment]
Hello, @naoliv !
First of all, thanks for giving the extension a try.
Then, you're absolutely correct blaming the separators. What is happening - because of steam arbitrary way of sending requested price, the current way of parsing it is not working correctly for your selected currencyId and you get NaN in the price field (left) and an actual comma-separated price on the right side, where the currency label should be.
Why did this happen - no matter what language prefs are, steam returns prices based on your location's currency.
I'm going to fix this asap.

**Comment by naoliv** [comment]
Great! Thanks a lot!

**Comment by naoliv** [comment]
Just tested it with the updated version and it's working as expected.
Thank you again.
