### ISSUE TITLE
Option to sell using the lowest value

### ISSUE THREAD

**Issue by naoliv** [k5md/Steam-Bulk-Sell-webextension#4]
Hi!

For example, I have this booster pack:

![](https://user-images.githubusercontent.com/982338/95923710-7685e100-0d8c-11eb-9d39-f34890e084da.png)

Where it's current minimum value is 0.98
I could put a sell offer of 0.97 and most probably I would sell it.

But when using the calculated median price:

![](https://user-images.githubusercontent.com/982338/95923810-b0ef7e00-0d8c-11eb-9cdd-067db2f68abb.png)

Which is way less than the current minimum value (and this will generate a loss).

Isn't it possible to have an option to use the current minimum value? (and maybe an option to use "current value - 0.01")

Thanks!

**Comment by k5md** [comment]
Hello and thanks again, @naoliv !
As it turned out, it's what they return, dunno, whether intential or not.
![steam_again](https://user-images.githubusercontent.com/6698666/95949690-e8494380-0dfb-11eb-88e9-247ce065cdc1.png)
I knew that steam may not include median price in response, so there is an explicit check for this, but median being lower than minimal value is something really unexpected and contradicting the definition of median.
It's simple, so I'll issue a fix in an hour.

**Comment by naoliv** [comment]
Great!
Thank you one more time!
