### ISSUE TITLE
"Missing parameters in SellItem request" while trying to sell

### ISSUE THREAD

**Issue by naoliv** [k5md/Steam-Bulk-Sell-webextension#6]
Hi!

While trying to sell some items I am seeing this:

```
[X] Civic Duty Mk.II War Paint (Well-Worn), {"success":false,"message":"Missing parameters in SellItem request"}
[X] Smalltown Bringdown Mk.II War Paint (Well-Worn), {"success":false,"message":"Missing parameters in SellItem request"}
[X] Civic Duty Mk.II War Paint (Well-Worn), {"success":false,"message":"Missing parameters in SellItem request"}
```

It seems that it tries 4 times to sell the same item (and always have the same error message).
I couldn't capture anything in Firefox's network monitor (to see what it's trying to request).

Is there anything that I can do to help with this, please?
The plugin version is `1.1.0`

**Comment by k5md** [comment]
Hello!
I was able to reproduce this error (by some occasion, only with Civic Duty Mk.II paint, I have sold Smalltown Bringdown Mk.II successfully, not sellable and other items yield other error messages) and will fix it either today or tomorrow.
It is an error from requesting steam api, in my case items are successfully put on marketplace, but inventory (the one that steam creates as window property) does not change! If you can, please, confirm if items were placed on marketplace, though steam request yielded error.
>It seems that it tries 4 times to sell the same item (and always have the same error message).
Yep, 3 additional retries with timeouts are default behaviour for failed requests, since when auto-selling, steam may reject requests for various reasons (like, incomplete action on their side, or requesting confirmation (though item is being placed on marketplace) or too low timeout between requests, or whatever).
>I couldn't capture anything in Firefox's network monitor (to see what it's trying to request).
Sadly, it is the extension's content script that is hooking (like adblock, for instance) to inventory page and is sending related requests and there seems to be no actual way to check what's wrong except for debugging dev build.

**Comment by k5md** [comment]
Hi, I've found it, actually, it was not steam's API fault, but mine, when I decided to do a quickfix for prices and used simple multiplication instead of any way of rounding, that resulted in sometimes appearing issue, when stringified formData price field is populated with float. Sort of trivial mistake, hopefully, this patch will fix it.

**Comment by naoliv** [comment]
It's working as expected.
Thank you one more time!
